name: Compilar EXE per a Windows (Projecte Electron)

on:
  workflow_dispatch:
    
jobs:
  build:
    runs-on: windows-latest

    steps:
    # 1. Descarrega el codi del teu repositori
    - name: Checkout del codi
      uses: actions/checkout@v4

    # 2. Configura l'entorn de Node.js per poder utilitzar npm
    - name: Configuració de Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20' # Utilitzem una versió recent de Node.js

    # 3. Instal·la totes les dependències del package.json
    - name: Instal·lació de dependències del projecte
      run: npm install
      
    - name: 4.5 Create google-credentials.json from secret
      env:
        CREDENTIALS_JSON: ${{ secrets.GOOGLE_CREDENTIALS_JSON }}
      run: echo "%CREDENTIALS_JSON%" > google-credentials.json
      shell: cmd

    - name: 4.6 Create service-account.json from secret
      env:
        SERVICE_JSON: ${{ secrets.SERVICE_ACCOUNT_JSON }}
      run: echo "%SERVICE_JSON%" > service-account.json
      shell: cmd

    - name: Comprova que google-credentials.json existeix i no està buit
      shell: cmd
      run: |
          if not exist google-credentials.json (
            echo "El fitxer google-credentials.json NO existeix!" && exit 1
          )
          for %%A in (google-credentials.json) do if %%~zA lss 10 (
            echo "El fitxer google-credentials.json està buit o massa petit!" && exit 1
          )

    # 4. PAS CLAU: Executa el teu script "build:electron"
    # Aquesta única comanda s'encarrega de compilar el teu codi React i empaquetar-lo amb Electron.
    # Els paràmetres --win --x64 asseguren que es construeixi per a Windows 64-bit.
    - name: Compilació i empaquetat de l'aplicació
      run: npm run build:electron -- --win --x64 --publish never

    # 5. Creació del paquet ZIP per a Windows
    - name: Crear paquet ZIP de Windows
      id: zip_windows
      shell: pwsh
      run: |
        $filesToZip = Get-ChildItem -Path "dist" -Filter "*.exe" | ForEach-Object { $_.FullName }
        $filesToZip += @("LICENSE", "README.md", "DEVELOPING.md")
        $filesToZip += Get-ChildItem -Path "examples json" -Recurse | ForEach-Object { $_.FullName }

        $zipName = "GestorEsdevenimentsPersonal_V1.3.0-Windows.zip"
        echo "zip_name=$zipName" >> $env:GITHUB_OUTPUT

        Compress-Archive -Path $filesToZip -DestinationPath $zipName

    # 6. Pujada de l'artefacte ZIP de Windows
    - name: Pujada del ZIP de Windows
      uses: actions/upload-artifact@v4
      with:
        name: ${{ steps.zip_windows.outputs.zip_name }}
        path: ${{ steps.zip_windows.outputs.zip_name }}