name: Compilar per a Linux (AppImage)

on:
  # El deixem amb activació manual per no molestar. El pots executar quan vulguis.
  workflow_dispatch:

jobs:
  build:
    # LÍNIA CLAU: Forcem a GitHub a utilitzar la mateixa base que tu (Ubuntu 20.04)
    runs-on: ubuntu-20.04

    steps:
      - name: 1. Checkout del codi
        uses: actions/checkout@v4

      - name: 2. Configuració de Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: 3. Instal·lació de dependències del sistema per a Ubuntu 20.04
        run: |
          sudo apt-get update
          # AQUESTA ÉS LA LLISTA ORIGINAL I CORRECTA PER A UBUNTU 20.04
          # Inclou el famós 'libgconf-2-4' que només existeix en aquesta versió.
          sudo apt-get install -y --no-install-recommends \
            libgconf-2-4 \
            libgtk-3-dev \
            libnss3 \
            libasound2 \
            libxtst-dev \
            libxss1 \
            libappindicator3-1

      - name: 4. Instal·lació de dependències del projecte (npm)
        run: npm install

      - name: 5. Compilació de l'aplicació per a Linux
        run: npm run build:electron -- --linux --x64 --publish never

      - name: 6. Pujada de l'AppImage com a artefacte
        uses: actions/upload-artifact@v4
        with:
          name: GestorEsdeveniments-Linux-AppImage
          path: dist/*.AppImage